### ISSUE TITLE
stuttering menu on iPad Pro 2020

### ISSUE THREAD

**Issue by NicolasHaeffner** [jellyfin/Swiftfin#124]
On the iPad Pro 2020 the menu feels like maybe 15 fps. On my iPhone X everything is fine and playback works as flawless as well.

**Comment by acvigue** [comment]
iOS v?

**Comment by NicolasHaeffner** [comment]
Sorry, its on 14.7.1

**Comment by PangMo5** [comment]
I wonder exactly what the `menu` means.

**Comment by NicolasHaeffner** [comment]
Okay, trying to be a little more specific: 
Starting with opening the app, the framerate drops. Even the opening animation of the app itself is stuttering.
Swiping in and out of the app (with 4  fingers sideways through all open apps) drops the framerate as soon as swiftfin is participating.
The main menu inside of swiftfin is at low fps (scrolling through shows/movies, the animation when the info is opened, the animation going back). 
It shows badly on a screencast (and I really don’t know how to capture one without revealing personal info) 

Maybe it‘s „because“ of the promotion display? Really speculating here though…

**Comment by acvigue** [comment]
I'm unable to reproduce this on my friend's Pro. Weird.

**Comment by PangMo5** [comment]
I'll check it too when I have time.

**Comment by TheNamelessWonderer** [comment]
Same issue on my iPad Air 2 on iOS 14.7.1. This videos shows it well on the movies section where it freezes as it tries to load everything but the main screen is also laggy like there is a delay when swiping but it’s not that clear on the video. https://imgur.com/a/tmomgDi

**Comment by acvigue** [comment]
This issue is limited to 14.7.1-15 DB 2. I noticed this on my phone but it is resolved in the latest preview of iOS 15. Closing.

**Comment by TheGreatestJannet** [comment]
Are you sure? I’ve been having the stutter since 14.7 or maybe earlier.

**Comment by TheNamelessWonderer** [comment]
Are you sure? I've been having it for a while now at least 14.7 or earlier but it might be because my iPad Air 2 is an old device now. My iPhone SE (1st Gen) on 14.7.1. does not have this lag on the home screen like my iPad.

**Comment by charleypeng** [comment]
i have an ipad pro 2020, it looks like that the fresh rate is low and lag

**Comment by mikemykhaylov** [comment]
I'm still having this issue on iPadOS 16.5.1 and Swiftfin 1.0.1 (78). Interestingly, scrolling side to side in the main menu is smooth and 120Hz, but up and down is very jittery
