### ISSUE TITLE
[tvOS] Some logos on the detail screen are cropped unexpectedly

### ISSUE THREAD

**Issue by tjdavey** [jellyfin/Swiftfin#1492]
### Describe the bug

When viewing the detail screens of movies and shows with a logo the logo appears to be cropped in unusual ways for some logos.

![Image](https://github.com/user-attachments/assets/ffb4d712-da1b-4388-94cf-b54f9cdb8301)

Source of logo: https://image.tmdb.org/t/p/original/nMYKB9QVawAzUO6d8VUhamUgqOJ.png

![Image](https://github.com/user-attachments/assets/3308a73c-8fed-4e96-9faf-c24758e346b1)

Source of logo: https://image.tmdb.org/t/p/original/xLresrupcXIq7AfeMc5V6XHCxd5.png

These logos appear normally on other screens and platforms and this does not impact all logos. 
 

### Application version

1.0.1 (70)

### Where did you install the app from?

App Store

### Device information

Apple TV 4K (3rd generation)

### OS version

TvOS 18.3 (22K557)

### Jellyfin server version

10.10.7

**Comment by JPKribs** [comment]
I believe this is resolved on our Main branch of tvOS. Our tvOS release a bit behind our iOS release. You can track our progress towards our next release here:

https://github.com/jellyfin/Swiftfin/discussions/1294

To confirm, would you be able to provide me with the image files for the logos and I can confirm that these are handled appropriately on the development branch.

**Comment by sjorge** [comment]
I tried with a few logo variants for golden eye and I cannot reproduce on main branch:

![Image](https://github.com/user-attachments/assets/bcecf3a3-0bbd-42ae-be68-c8ffe65f0c38)

![Image](https://github.com/user-attachments/assets/e77e3dbb-5d9e-402c-94c5-ba4bb962023b)

But there was no ridiculously large logo available I could pick to see if that is fine though.

**Comment by tjdavey** [comment]
> I believe this is resolved on our Main branch of tvOS. Our tvOS release a bit behind our iOS release. You can track our progress towards our next release here:
> 
> [#1294](https://github.com/jellyfin/Swiftfin/discussions/1294)
> 
> To confirm, would you be able to provide me with the image files for the logos and I can confirm that these are handled appropriately on the development branch.

The links for the files from tmdb are above in my original post, but I have attached them for your convenience. 

![Image](https://github.com/user-attachments/assets/d3fd1259-15b7-4d83-b923-8582c7b40930)
![Image](https://github.com/user-attachments/assets/d761337f-4657-432e-89a8-e9cdca6e934b)

**Comment by JPKribs** [comment]
Tested and can confirm these do not cause issues on the Main branch for tvOS. I will leave this open to track this issue but it should require no further development to resolve. You can follow our progress towards our next tvOS release here:

https://github.com/jellyfin/Swiftfin/discussions/1294

**Comment by LePips** [comment]
Considering closed after #2075. Re-report if still present after tvOS 1.5 release.
