### ISSUE TITLE
Library Update

### ISSUE THREAD

**Issue by jrnas** [jellyfin/Swiftfin#784]
TVOS: Please develop a feature or a settings option for a automatically library refresh, because it doesn’t refresh the library 

**Additional context**

**Comment by dalehumby** [comment]
To expand on this feature request a bit:

Once the app is launched the Apple TV library is not updated when new shows/movies are added on Jellyfin server. The app needs to be restarted (Double-tap the TV button on the remote. Then swipe up on the app to terminate) and then relaunched for new content to show.

**To recreate:**
1. Launch Jellyfin on Apple TV. Exit Jellyfin app, launch another app. Or turn off the Apple TV (press hold middle button, Power Off)
2. Using radarr etc., a new movie is added and Jellyfin server imports the movie (it's available through the web player, with all metadata)
3. Turn on Apple TV, open Jellyfin
4. New movies/show is not availabe
5. Terminate Jellyfin app (Double-tap the TV button on the remote. Then swipe up on the app to terminate.)
6. Relaunch Jellyfin, the movie is now available

Ideally the content can be lazy-loaded, so when the app is open new content shows up after a few seconds. 

Personally I don't think this needs to be a setting, just something the app does in the background.

**Comment by github-bryld** [comment]
Seconded.
Oddly, the library seems to refresh automatically on iOS/iPadOS, it only fails on TVOS.

**Comment by kSapewpew** [comment]
This is still an issue. Any way one can help with on this one? It's making it rather annoying to use Swiftfin at the moment.

**Comment by sIRwa2** [comment]
Is this issue acknowledged and on the road map to be fixed is one way or another? a "refresh library" button would already help until auto refresh is solved imo.

**Comment by Nanorulez123** [comment]
Still an issue

**Comment by KintsugiUwU** [comment]
> Seconded. Oddly, the library seems to refresh automatically on iOS/iPadOS, it only fails on TVOS.

It isn't working for me on iPad OS. Added a new library with videos from YouTube. Jellyfin mobile has the updated library but SwiftFin not

**Comment by foorschtbar** [comment]
I can see the same behavior under tvOS - the app has to be restarted after every library update. Would be nice if someone could take a look at this. Automatically or, if necessary, with a button.

**Comment by h4knet** [comment]
Hi,
I can confirm the issue on Apple TV.
The only workaround is to reboot the Apple TV 😓

**Comment by JPKribs** [comment]
Please note this is completed in the Main build of Swiftfin for tvOS. This will be included in our next tvOS release. You can follow our progress for that here:

https://github.com/jellyfin/Swiftfin/discussions/1294

**Comment by rbrianharris** [comment]
As of January 2026 this is still an issue.  I'm running updated everything.

**Comment by tobiasbischoff** [comment]
Some one please implement this I have to reboot the ATV everytime to see new movies

**Comment by austinbaccus** [comment]
> Please note this is completed in the Main build of Swiftfin for tvOS. This will be included in our next tvOS release. You can follow our progress for that here:
> 
> [#1294](https://github.com/jellyfin/Swiftfin/discussions/1294)

Sorry if this is a dumb question, but I still see it in `unassigned` and this issue is still open with no code related to it. Does this mean it was completed somewhere else or something?

**Comment by JPKribs** [comment]
> Sorry if this is a dumb question, but I still see it in unassigned and this issue is still open with no code related to it. Does this mean it was completed somewhere else or something?

The item is resolved in Main but we don't want to close this issue until it's in the App Store to leave a place to track.

I've updated the notes to reflect this.

**Comment by sugan96** [comment]
@JPKribs would this fix also resolve the UI not reloading after an episode or a movie finishes?

Edit: tested `master`, looks like it's been fixed. Thanks! Looking forward to release 🙏🏽

**Comment by orehmane** [comment]
Hi there, I'm on the latest version that was just released, and this problem seems to persist for me. If I watch an episode or two of something, then go back to the Swiftfin home screen, it does not update (still shows the same thing as when I first loaded in).

It does update if I switch users or force close the app. Is there a setting or something I need to change to make it work properly?

**Comment by bninot** [comment]
I confirm, I am in TestFlight version 1.6 build 15 on tvOS 26 and the problem of automatic refresh of the interface is still present.

**Comment by Prolonz** [comment]
Hi @JPKribs 

If you have a chance it would be great to have an update on the current status of this issue. The Swiftfin - Roadmap shows as In-Progress/Completed in Main. And your comment indicated that it would be fixed in the version we have now. 

> Please note this is completed in the Main build of Swiftfin for tvOS. This will be included in our next tvOS release. You can follow our progress for that here:
> 
> [#1294](https://github.com/jellyfin/Swiftfin/discussions/1294)

Was the work that had previously addressed this issue removed in one of the large PRs? 

Personally, this would be the biggest QOL feature to include in a future release.

**Comment by JPKribs** [comment]
> Was the work that had previously addressed this issue removed in one of the large PRs?

There is some work on that front, like the home view refreshes at an interval when other tabs are focused. However the reason this issue is still open is because there is more work.

This would be a `notificationManger`, likely a `UserSessionService` that would take centralize updates from throughout the app and take in socket updates for `UserData`. I had something I started before the socket was complete but the socket updates will be an important part of it.

It's definitely on the list but no ETA just yet but I'll update this thread when something changes
